<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.1.1.386
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Ankieta o tatuażu zgłoszenie',
	'heading' => 'Przesłano nowy formularz',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Zaznaczone',
		'checkbox_unchecked' => 'Niezaznaczone',
		'submitted_from' => 'Formularz wysłany z witryny:%s',
		'submitted_by' => 'Adres IP gościa:%s',
		'too_many_submissions' => 'Z tego IP przesłano ostatnio zbyt wiele zgłoszeń',
		'failed_to_send_email' => 'Nie udało się wysłać wiadomości e-mail',
		'invalid_reCAPTCHA_private_key' => 'Nieprawidłowy klucz prywatny reCAPTCHA.',
		'invalid_reCAPTCHA2_private_key' => 'Nieprawidłowy klucz prywatny reCAPTCHA 2.0.',
		'invalid_reCAPTCHA2_server_response' => 'Nieprawidłowa odpowiedź serwera reCAPTCHA 2.0.',
		'invalid_field_type' => 'Nieznany typ pola „%s”.',
		'invalid_form_config' => 'Pole „%s” ma nieprawidłową konfigurację.',
		'unknown_method' => 'Nieznana metoda żądania serwera'
	),
	'email' => array(
		'from' => 'kamilszurlej123@gmail.com',
		'to' => 'kamilszurlej123@gmail.com'
	),
	'fields' => array(
		'custom_U3430' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Dlaczego?',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U15487' => array(
			'order' => 2,
			'type' => 'radiogroup',
			'label' => 'czy posiadasz tatuaż?',
			'required' => true,
			'optionItems' => array(
				'Tak',
				'Nie'
			),
			'errors' => array(
				'required' => 'Pole „czy posiadasz tatuaż?” jest wymagane.',
				'format' => 'Wartość znajdująca się w polu „czy posiadasz tatuaż?” jest nieprawidłowa.'
			)
		),
		'custom_U21093' => array(
			'order' => 1,
			'type' => 'radiogroup',
			'label' => 'Podaj swój wiek',
			'required' => true,
			'optionItems' => array(
				'poniżej 18 lat',
				'18 - 26 lat',
				'27 - 35 lat',
				'36 - 50 lat',
				'powyżej 50 lat'
			),
			'errors' => array(
				'required' => 'Pole „Podaj swój wiek” jest wymagane.',
				'format' => 'Wartość znajdująca się w polu „Podaj swój wiek” jest nieprawidłowa.'
			)
		),
		'custom_U21400' => array(
			'order' => 3,
			'type' => 'radiogroup',
			'label' => 'czy chciałbyś mieć tatuaż?',
			'required' => true,
			'optionItems' => array(
				'tak',
				'nie'
			),
			'errors' => array(
				'required' => 'Pole „czy chciałbyś mieć tatuaż?” jest wymagane.',
				'format' => 'Wartość znajdująca się w polu „czy chciałbyś mieć tatuaż?” jest nieprawidłowa.'
			)
		)
	)
);

process_form($form);
?>
